[build]
  # Build command for Python Flask app
  command = "pip install -r requirements.txt"
  
  # Publish directory (where the built site files are located)
  publish = "."
  
  # Functions directory for serverless functions
  functions = "netlify/functions"

[build.environment]
  # Python version
  PYTHON_VERSION = "3.9"

# Redirect rules for SPA
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
